export const DataTypeColors = {
  AMOUNT: 'AMOUNT',
  LITER: 'LITER',
  CELCIUS: 'CELCIUS',
  HUMIDITY: 'HUMIDITY',
  LIGHT_INTENSITY: 'LIGHT INTENSITY',
  ACCELERATION: 'ACCELERATION',
  METER: 'METER',
  MAGNETIC_FIELD: 'MAGNETIC FIELD',
  VOLTAGE: 'VOLTAGE',
  CURRENT: 'CURRENT',
  PRESSURE: 'PRESSURE'
}
export default {
  DataTypeColors
}
